/* Neon Notes v1.0 — single-user IndexedDB app, schema version 1 */
(() => {
  "use strict";
  const $ = s => document.querySelector(s);
  const DB_NAME = "NeonNotesDB", DB_VERSION = 1, NOTES_STORE = "notes", CATEGORIES_STORE = "categories";
  const palette = ["#168cff", "#8b5cf6", "#12c99b", "#ffb938", "#f472b6", "#22d3ee"];
  const defaultCategories = [{name:"General",color:palette[0]},{name:"Ideas",color:palette[1]},{name:"Work",color:palette[2]},{name:"Personal",color:palette[3]}];
  const seedNotes = [
    {title:"Welcome to Neon Notes",body:"Hey there! 👋\n\nThis is your personal space for ideas, plans, and everything worth remembering.\n\nWHAT YOU CAN DO\n• Create, edit, and delete notes\n• Search, pin, tag, and categorize notes\n• Format text with the rich editor\n• Export a backup whenever you need\n\nYour ideas, your space. ✨",category:"General",pinned:true,tags:["welcome","guide"],age:120000},
    {title:"Project Ideas",body:"1. Build Neon OS\n2. Improve the notes app\n3. Experiment with browser databases\n4. Make a tiny game",category:"Ideas",pinned:false,tags:["coding","projects"],age:21600000},
    {title:"Study Plan",body:"JavaScript — 2h\nIndexedDB — 1h\nBuild projects — 2h\nReview notes — 30m",category:"Work",pinned:false,tags:["study"],age:86400000},
    {title:"Shopping List",body:"Milk\nEggs\nBread\nRice\nChicken\nVegetables",category:"Personal",pinned:false,tags:["shopping"],age:172800000},
    {title:"Notes App Features",body:"Rich text editor\nTags\nSearch\nPinned notes\nCategories\nIndexedDB persistence",category:"Ideas",pinned:false,tags:["features","coding"],age:259200000}
  ];
  let db, notes=[], categories=[], selectedId=null, activeFilter="all", activeCategory=null, activeTag="", categoryExpanded=true, saveTimer=null, toastTimer=null, hydrating=false;
  let sortMode="updated", viewMode="grid";
  const makeId=()=>window.crypto?.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const normalize=s=>String(s||"").replace(/\\r\\n|\\n|\\r/g,"\n");
  const textOf=html=>{const d=document.createElement("div");d.innerHTML=html||"";return d.textContent||d.innerText||"";};
  const plainToHtml=value=>esc(normalize(value)).replace(/\n/g,"<br>");
  function sanitizeHtml(html){const template=document.createElement("template");template.innerHTML=html||"";const allowed=new Set(["B","STRONG","I","EM","U","BR","P","DIV","UL","OL","LI","H2","BLOCKQUOTE","A"]);const walk=node=>{[...node.childNodes].forEach(child=>{if(child.nodeType===1){if(!allowed.has(child.tagName)){child.replaceWith(document.createTextNode(child.textContent||""));return;}[...child.attributes].forEach(attr=>{if(child.tagName!=="A"||attr.name!=="href"||!/^https?:|^mailto:/i.test(attr.value))child.removeAttribute(attr.name);});walk(child);}else if(child.nodeType!==3)child.remove();});};walk(template.content);return template.innerHTML;}
  const req=request=>new Promise((res,rej)=>{request.onsuccess=()=>res(request.result);request.onerror=()=>rej(request.error||Error("IndexedDB request failed"));});
  const done=tx=>new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error||Error("Transaction failed"));tx.onabort=()=>rej(tx.error||Error("Transaction aborted"));});
  function openDB(){return new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(Error("IndexedDB unavailable in this preview."));const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains(NOTES_STORE)){const s=d.createObjectStore(NOTES_STORE,{keyPath:"id"});s.createIndex("updatedAt","updatedAt");s.createIndex("pinned","pinned");}if(!d.objectStoreNames.contains(CATEGORIES_STORE))d.createObjectStore(CATEGORIES_STORE,{keyPath:"name"});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
  async function all(store){const tx=db.transaction(store,"readonly"),out=await req(tx.objectStore(store).getAll());await done(tx);return out;}
  async function put(store,value){const tx=db.transaction(store,"readwrite");tx.objectStore(store).put(value);await done(tx);}
  async function del(store,key){const tx=db.transaction(store,"readwrite");tx.objectStore(store).delete(key);await done(tx);}
  async function seed(){if(!(await all(NOTES_STORE)).length){const now=Date.now(),tx=db.transaction(NOTES_STORE,"readwrite"),s=tx.objectStore(NOTES_STORE);seedNotes.forEach(n=>s.put({id:makeId(),title:n.title,body:n.body,category:n.category,pinned:n.pinned,tags:n.tags,createdAt:now-n.age,updatedAt:now-n.age}));await done(tx);}if(!(await all(CATEGORIES_STORE)).length){const tx=db.transaction(CATEGORIES_STORE,"readwrite");defaultCategories.forEach(c=>tx.objectStore(CATEGORIES_STORE).put(c));await done(tx);}}
  async function load(){[notes,categories]=await Promise.all([all(NOTES_STORE),all(CATEGORIES_STORE)]);for(const n of notes){let changed=false;let body=normalize(n.body);if(body!==n.body){n.body=body;changed=true;}if(body&&!/<\/?(b|strong|i|em|u|br|p|div|ul|ol|li|h2|blockquote|a)(\s|>)/i.test(body)){n.body=plainToHtml(body);changed=true;}else if(body){const clean=sanitizeHtml(body);if(clean!==body){n.body=clean;changed=true;}}if(!Array.isArray(n.tags)){n.tags=[];changed=true;}if(changed)await put(NOTES_STORE,n);}if(!selectedId||!notes.some(n=>n.id===selectedId))selectedId=notes[0]?.id||null;}
  function date(ts){const d=Math.max(0,Date.now()-ts);if(d<60000)return"Just now";if(d<3600000)return`${Math.floor(d/60000)}m ago`;if(d<86400000)return`${Math.floor(d/3600000)}h ago`;if(d<172800000)return"Yesterday";return`${Math.floor(d/86400000)}d ago`;}
  function catInfo(name){return categories.find(c=>c.name===name)||categories[0]||{name:"General",color:palette[0]};}
  function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2400);}
  function filteredNotes(){const q=$("#searchInput").value.trim().toLowerCase();let out=notes.filter(n=>(activeFilter!=="pinned"||n.pinned)&&(!activeCategory||n.category===activeCategory)&&(!activeTag||(n.tags||[]).some(t=>t.toLowerCase()===activeTag.toLowerCase()))&&(!q||`${n.title} ${textOf(n.body)} ${n.category} ${(n.tags||[]).join(" ")}`.toLowerCase().includes(q)));out.sort((a,b)=>{if(sortMode==="title")return(a.title||"").localeCompare(b.title||"");if(sortMode==="created")return b.createdAt-a.createdAt;if(sortMode==="oldest")return a.updatedAt-b.updatedAt;return Number(b.pinned)-Number(a.pinned)||b.updatedAt-a.updatedAt;});return out;}
  function renderCategories(){const list=$("#categoryList");list.innerHTML=categories.map(c=>`<button class="category-item ${activeCategory===c.name?"active":""}" data-category="${esc(c.name)}"><span class="category-dot" style="--dot:${c.color}"></span><span>${esc(c.name)}</span><span class="count">${notes.filter(n=>n.category===c.name).length}</span></button>`).join("");list.classList.toggle("hidden",!categoryExpanded);}
  function renderTagFilter(){const tags=[...new Set(notes.flatMap(n=>n.tags||[]))].sort((a,b)=>a.localeCompare(b));$("#tagFilter").innerHTML='<option value="">All tags</option>'+tags.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join("");$("#tagFilter").value=activeTag;}
  function renderNotes(){const list=$("#notesList"),items=filteredNotes();list.className=`notes-list view-${viewMode}`;list.innerHTML=items.map(n=>{const c=catInfo(n.category),preview=textOf(n.body).replace(/\s+/g," ").trim()||"No additional text";return `<div class="note-card ${n.id===selectedId?"selected":""}" data-id="${esc(n.id)}" tabindex="0" role="button"><div class="note-card-top">${n.pinned?'<span class="note-pin">◆</span>':""}<span class="note-card-title">${esc(n.title||"Untitled note")}</span><span class="note-date">${date(n.updatedAt)}</span></div><div class="note-card-category"><span class="category-dot" style="--dot:${c.color}"></span>${esc(n.category||"General")}</div>${(n.tags||[]).length?`<div class="note-tags">${n.tags.map(t=>`<span class="tag-chip">#${esc(t)}</span>`).join("")}</div>`:""}<div class="note-preview">${esc(preview)}</div><button class="card-menu" data-menu="${esc(n.id)}" title="Delete note" aria-label="Delete note">⋮</button></div>`;}).join("");$("#emptyState").classList.toggle("hidden",items.length>0);$("#visibleCount").textContent=`${items.length} ${items.length===1?"NOTE":"NOTES"}`;$("#allCount").textContent=notes.length;$("#pinnedCount").textContent=notes.filter(n=>n.pinned).length;$("#listTitle").textContent=activeTag?`#${activeTag}`:activeCategory|| (activeFilter==="pinned"?"Pinned Notes":"All Notes");renderCategories();renderTagFilter();}
  function openEditor(){$("#editorPanel").classList.add("is-open");$("#editorBackdrop").classList.remove("hidden");document.body.classList.add("editor-open");}
  async function closeEditor(){if(saveTimer)await saveNote(false);$("#editorPanel").classList.remove("is-open");$("#editorBackdrop").classList.add("hidden");document.body.classList.remove("editor-open");}
  function renderEditor(){const n=notes.find(x=>x.id===selectedId),empty=!n;$("#editorEmpty").classList.toggle("hidden",!empty);$("#noteEditor").classList.toggle("hidden",empty);["#pinBtn","#categoryBtn","#deleteBtn","#saveBtn","#tagsInput"].forEach(s=>$(s).disabled=empty);if(empty){$("#editorStatus").textContent="NO NOTE SELECTED";return;}hydrating=true;$("#noteTitle").value=n.title||"";$("#noteBody").innerHTML=n.body||"";$("#tagsInput").value=(n.tags||[]).join(", ");hydrating=false;const c=catInfo(n.category);$("#categoryDot").style.background=c.color;$("#currentCategory").textContent=n.category||"General";$("#createdMeta").textContent=`Created ${date(n.createdAt)}`;$("#updatedMeta").textContent=`Edited ${date(n.updatedAt)}`;$("#pinBtn").classList.toggle("on",!!n.pinned);$("#pinBtn").title=n.pinned?"Unpin note":"Pin note";$("#editorStatus").textContent="SAVED TO INDEXEDDB";updateWordCount();}
  function render(){renderNotes();renderEditor();}
  function scheduleSave(){if(hydrating)return;clearTimeout(saveTimer);$("#editorStatus").textContent="UNSAVED CHANGES…";saveTimer=setTimeout(()=>saveNote(false),500);}
  async function saveNote(show=true){clearTimeout(saveTimer);saveTimer=null;const n=notes.find(x=>x.id===selectedId);if(!n)return;n.title=$("#noteTitle").value.trim();n.body=sanitizeHtml($("#noteBody").innerHTML);n.tags=[...new Set($("#tagsInput").value.split(",").map(t=>t.trim().replace(/^#/,"")).filter(Boolean))];n.updatedAt=Date.now();try{await put(NOTES_STORE,n);$("#editorStatus").textContent="ALL CHANGES SAVED";$("#updatedMeta").textContent=`Edited ${date(n.updatedAt)}`;renderNotes();if(show)toast("Note saved");}catch(e){$("#editorStatus").textContent="SAVE FAILED";toast("Save failed: "+e.message);}}
  async function createNote(){if(selectedId)await saveNote(false);const now=Date.now(),n={id:makeId(),title:"",body:"",category:activeCategory||"General",pinned:false,tags:[],createdAt:now,updatedAt:now};try{await put(NOTES_STORE,n);notes.unshift(n);selectedId=n.id;activeFilter="all";activeCategory=null;activeTag="";$("#searchInput").value="";document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.filter==="all"));render();openEditor();$("#noteTitle").focus();toast("New note created");}catch(e){toast("Could not create note: "+e.message);}}
  async function deleteNote(id=selectedId){const n=notes.find(x=>x.id===id);if(!n||!confirm(`Delete “${n.title||"Untitled note"}”?`))return;clearTimeout(saveTimer);try{await del(NOTES_STORE,id);notes=notes.filter(x=>x.id!==id);selectedId=notes[0]?.id||null;render();toast("Note deleted");}catch(e){toast("Delete failed: "+e.message);}}
  function pickCategory(){ $("#categoryOptions").innerHTML=categories.map(c=>`<button class="category-option" type="button" data-pick-category="${esc(c.name)}"><span class="category-dot" style="--dot:${c.color}"></span>${esc(c.name)}</button>`).join("");$("#categoryPickDialog").showModal();}
  function updateWordCount(){const t=textOf($("#noteBody").innerHTML).trim();$("#wordCount").textContent=`${t?t.split(/\s+/).length:0} words`;}
  function execFormat(command,value=null){$("#noteBody").focus();if(command==="formatBlock")document.execCommand("formatBlock",false,"<h2>");else document.execCommand(command,false,value);scheduleSave();updateWordCount();}
  function applyAccent(color){document.documentElement.style.setProperty("--accent",color);document.documentElement.style.setProperty("--purple",color);document.documentElement.style.setProperty("--purple-2",color);try{localStorage.setItem("neonNotesAccent",color);}catch(_){}}
  function exportBackup(){const data={app:"Neon Notes",formatVersion:1,exportedAt:new Date().toISOString(),databaseVersion:1,notes,categories};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`neon-notes-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);toast("Backup exported");}
  async function importBackup(file){if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.notes)||!Array.isArray(data.categories))throw Error("This file is not a Neon Notes backup.");if(!confirm("Import backup? Matching note IDs will be replaced; other notes remain."))return;for(const n of data.notes){if(!n.id)continue;n.body=/<\/?(b|strong|i|em|u|br|p|div|ul|ol|li|h2|blockquote|a)(\s|>)/i.test(String(n.body||""))?sanitizeHtml(n.body):plainToHtml(n.body);n.tags=Array.isArray(n.tags)?n.tags:[];n.createdAt=Number(n.createdAt)||Date.now();n.updatedAt=Number(n.updatedAt)||Date.now();await put(NOTES_STORE,n);}for(const c of data.categories){if(c.name)await put(CATEGORIES_STORE,c);}await load();render();toast("Backup restored");}catch(e){toast("Import failed: "+e.message);}finally{$("#importFile").value="";}}
  function openPalette(){$("#commandDialog").showModal();$("#commandInput").value="";renderCommands();$("#commandInput").focus();}
  function renderCommands(){const q=$("#commandInput").value.toLowerCase(),commands=[ ["Create new note",createNote],["Focus search",()=>$("#searchInput").focus()],["Export backup",exportBackup],["Toggle theme",()=>$("#themeBtn").click()],["Switch to Grid view",()=>setView("grid")],["Switch to List view",()=>setView("list")],["Switch to Compact view",()=>setView("compact")],["Open accent color",()=>$("#accentPicker").click()] ].filter(c=>c[0].toLowerCase().includes(q));$("#commandResults").innerHTML=commands.map((c,i)=>`<button class="command-option" data-command="${i}">${esc(c[0])}<span>↵</span></button>`).join("")||"<p>No matching commands</p>";$("#commandResults")._commands=commands;}
  function setView(v){viewMode=v;document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));renderNotes();try{localStorage.setItem("neonNotesView",v);}catch(_){}}
  // Core actions
  $("#newNoteBtn").addEventListener("click",createNote);$("#emptyNewBtn").addEventListener("click",createNote);$("#saveBtn").addEventListener("click",()=>saveNote(true));$("#closeEditorBtn").addEventListener("click",closeEditor);$("#editorBackdrop").addEventListener("click",closeEditor);
  ["#noteTitle","#tagsInput"].forEach(s=>$(s).addEventListener("input",scheduleSave));$("#noteBody").addEventListener("input",()=>{scheduleSave();updateWordCount();});$("#deleteBtn").addEventListener("click",()=>deleteNote());
  $("#pinBtn").addEventListener("click",async()=>{const n=notes.find(x=>x.id===selectedId);if(!n)return;n.pinned=!n.pinned;n.updatedAt=Date.now();await put(NOTES_STORE,n);render();toast(n.pinned?"Note pinned":"Note unpinned");});$("#categoryBtn").addEventListener("click",pickCategory);
  $("#categoryOptions").addEventListener("click",async e=>{const b=e.target.closest("[data-pick-category]");if(!b)return;const n=notes.find(x=>x.id===selectedId);if(n){n.category=b.dataset.pickCategory;n.updatedAt=Date.now();await put(NOTES_STORE,n);}$("#categoryPickDialog").close();render();toast("Category updated");});
  $("#notesList").addEventListener("click",e=>{const menu=e.target.closest("[data-menu]");if(menu){e.stopPropagation();deleteNote(menu.dataset.menu);return;}const card=e.target.closest("[data-id]");if(!card)return;if(selectedId!==card.dataset.id){saveNote(false).then(()=>{selectedId=card.dataset.id;render();openEditor();});}else openEditor();});
  $("#notesList").addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&e.target.matches(".note-card")){e.preventDefault();selectedId=e.target.dataset.id;render();openEditor();}});
  document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>{activeFilter=b.dataset.filter;activeCategory=null;activeTag="";document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x===b));renderNotes();}));
  $("#categoryList").addEventListener("click",e=>{const b=e.target.closest("[data-category]");if(!b)return;activeCategory=b.dataset.category;activeTag="";activeFilter="all";document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));renderNotes();});
  $("#searchInput").addEventListener("input",renderNotes);$("#clearSearchBtn").addEventListener("click",()=>{$("#searchInput").value="";renderNotes();$("#searchInput").focus();});$("#tagFilter").addEventListener("change",()=>{activeTag=$("#tagFilter").value;renderNotes();});$("#sortSelect").addEventListener("change",()=>{sortMode=$("#sortSelect").value;renderNotes();});
  $("#categoryToggle").addEventListener("click",()=>{categoryExpanded=!categoryExpanded;renderCategories();});$("#addCategoryBtn").addEventListener("click",()=>{$("#categoryNameInput").value="";$("#categoryDialog").showModal();$("#categoryNameInput").focus();});
  $("#createCategoryBtn").addEventListener("click",async e=>{e.preventDefault();const name=$("#categoryNameInput").value.trim();if(!name)return toast("Enter a category name");if(categories.some(c=>c.name.toLowerCase()===name.toLowerCase()))return toast("Category already exists");const c={name,color:palette[categories.length%palette.length]};await put(CATEGORIES_STORE,c);categories.push(c);$("#categoryDialog").close();render();toast("Category created");});
  $("#themeBtn").addEventListener("click",()=>{document.body.classList.toggle("light");const light=document.body.classList.contains("light");$("#themeBtn").textContent=light?"☾":"☼";try{localStorage.setItem("neonNotesTheme",light?"light":"dark");}catch(_){}});
  $("#accentPicker").addEventListener("input",e=>applyAccent(e.target.value));$("#backupBtn").addEventListener("click",()=>$("#backupDialog").showModal());$("#exportBtn").addEventListener("click",()=>{exportBackup();$("#backupDialog").close();});$("#importBtn").addEventListener("click",()=>{$("#backupDialog").close();$("#importFile").click();});$("#importFile").addEventListener("change",e=>importBackup(e.target.files[0]));
  document.querySelectorAll("[data-format]").forEach(b=>b.addEventListener("click",()=>execFormat(b.dataset.format,b.dataset.block||null)));$("#formatColor").addEventListener("input",e=>execFormat("foreColor",e.target.value));
  document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));
  $("#commandBtn").addEventListener("click",openPalette);$("#commandInput").addEventListener("input",renderCommands);$("#commandInput").addEventListener("keydown",e=>{if(e.key==="Enter")$("#commandResults .command-option")?.click();});$("#commandResults").addEventListener("click",e=>{const b=e.target.closest("[data-command]");if(!b)return;const commands=$("#commandResults")._commands||[],command=commands[Number(b.dataset.command)];$("#commandDialog").close();command?.[1]();});
  document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openPalette();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="s"){e.preventDefault();saveNote(true);}if(e.key==="Escape"&&$("#editorPanel").classList.contains("is-open")){closeEditor();return;}if(e.key==="Escape"&&$("#searchInput")===document.activeElement)$("#searchInput").blur();});
  window.addEventListener("beforeunload",()=>{if(saveTimer)saveNote(false);});
  (async()=>{try{db=await openDB();await seed();await load();try{if(localStorage.getItem("neonNotesTheme")==="light"){document.body.classList.add("light");$("#themeBtn").textContent="☾";}const accent=localStorage.getItem("neonNotesAccent");if(accent){applyAccent(accent);$("#accentPicker").value=accent;}const view=localStorage.getItem("neonNotesView");if(["grid","list","compact"].includes(view))setView(view);}catch(_){}$("#storageStatus").textContent="IndexedDB connected · Local only";render();}catch(e){$("#storageStatus").textContent="Database unavailable";$("#editorStatus").textContent="DATABASE ERROR";toast(e.message||"Neon Notes could not start");console.error(e);}})();
})();
/* Neon Notes v1.1 productivity add-on */
(()=>{'use strict';const $=s=>document.querySelector(s);const KEY='neonNotesV11';let state={folders:['Inbox'],tasks:[],quick:[],daily:{}};try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(_){}const save=()=>localStorage.setItem(KEY,JSON.stringify(state));const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const style=document.createElement('style');style.textContent=`.v11-tools{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.v11-btn{border:1px solid #ffffff20;background:var(--accent,#7c3cff);color:white;border-radius:9px;padding:8px 10px;cursor:pointer;font:inherit}.v11-panel{position:fixed;z-index:9999;right:22px;bottom:22px;width:min(360px,calc(100vw - 32px));background:#171824;color:#f5f5ff;border:1px solid #ffffff25;border-radius:16px;padding:16px;box-shadow:0 18px 60px #0008}.v11-panel input,.v11-panel textarea,.v11-panel select{box-sizing:border-box;width:100%;margin:6px 0;padding:10px;border-radius:8px;border:1px solid #ffffff25;background:#252638;color:inherit}.v11-row{display:flex;gap:8px;align-items:center;margin:7px 0}.v11-row span{flex:1;overflow-wrap:anywhere}.v11-close{float:right;background:transparent;color:inherit;border:0;font-size:20px;cursor:pointer}.v11-small{opacity:.7;font-size:12px}`;document.head.append(style);
const tools=document.createElement('div');tools.className='v11-tools';tools.innerHTML='<button class="v11-btn" id="v11Daily">☀ Daily Note</button><button class="v11-btn" id="v11Tasks">✓ Tasks</button><button class="v11-btn" id="v11Quick">＋ Quick Note</button><button class="v11-btn" id="v11Folders">▣ Folders</button><button class="v11-btn" id="v11Backup">↕ V1.1 Backup</button><input id="v11Restore" type="file" accept="application/json" hidden>';$('.notes-column')?.prepend(tools);
function panel(title,html){document.querySelector('.v11-panel')?.remove();const p=document.createElement('section');p.className='v11-panel';p.innerHTML=`<button class="v11-close" aria-label="Close">×</button><h3>${title}</h3>${html}`;document.body.append(p);p.querySelector('.v11-close').onclick=()=>p.remove();return p}
function renderTasks(p){p.querySelector('#v11TaskList').innerHTML=state.tasks.map((t,i)=>`<div class="v11-row"><input type="checkbox" data-done="${i}" ${t.done?'checked':''}><span style="${t.done?'text-decoration:line-through;opacity:.55':''}">${esc(t.text)}${t.due?` <small>· ${esc(t.due)}</small>`:''}</span><button data-del="${i}">×</button></div>`).join('')||'<p class="v11-small">No tasks yet.</p>';p.querySelectorAll('[data-done]').forEach(x=>x.onchange=()=>{state.tasks[+x.dataset.done].done=x.checked;save();renderTasks(p)});p.querySelectorAll('[data-del]').forEach(x=>x.onclick=()=>{state.tasks.splice(+x.dataset.del,1);save();renderTasks(p)});}
$('#v11Tasks').onclick=()=>{const p=panel('Task Tracker','<input id="v11TaskText" placeholder="What needs doing?"><input id="v11TaskDue" type="date"><button class="v11-btn" id="v11AddTask">Add task</button><div id="v11TaskList"></div>');p.querySelector('#v11AddTask').onclick=()=>{const text=p.querySelector('#v11TaskText').value.trim();if(!text)return;state.tasks.unshift({text,due:p.querySelector('#v11TaskDue').value,done:false});save();renderTasks(p);p.querySelector('#v11TaskText').value=''};renderTasks(p)};
$('#v11Quick').onclick=()=>{const p=panel('Quick Note','<textarea id="v11QuickText" rows="5" placeholder="Capture a thought..."></textarea><button class="v11-btn" id="v11SaveQuick">Save quick note</button><div id="v11QuickList"></div>');p.querySelector('#v11QuickList').innerHTML=state.quick.map((q,i)=>`<div class="v11-row"><span>${esc(q)}</span><button data-qdel="${i}">×</button></div>`).join('');p.querySelector('#v11SaveQuick').onclick=()=>{const v=p.querySelector('#v11QuickText').value.trim();if(v){state.quick.unshift(v);save();p.remove();$('#v11Quick').click()}};p.querySelectorAll('[data-qdel]').forEach(b=>b.onclick=()=>{state.quick.splice(+b.dataset.qdel,1);save();p.remove();$('#v11Quick').click()})};
$('#v11Daily').onclick=()=>{const day=new Date().toISOString().slice(0,10);const p=panel('Daily Note · '+day,'<textarea id="v11DailyText" rows="8" placeholder="Plan your day, capture thoughts..."></textarea><button class="v11-btn" id="v11SaveDaily">Save daily note</button>');p.querySelector('#v11DailyText').value=state.daily[day]||'';p.querySelector('#v11SaveDaily').onclick=()=>{state.daily[day]=p.querySelector('#v11DailyText').value;save();p.remove()}};
$('#v11Folders').onclick=()=>{const p=panel('Folders & subfolders','<p class="v11-small">Organize with nested folder paths (e.g. School/JUPEB).</p><input id="v11FolderName" placeholder="Folder or Parent/Child"><button class="v11-btn" id="v11AddFolder">Add folder</button><div id="v11FolderList"></div>');const list=()=>p.querySelector('#v11FolderList').innerHTML=state.folders.map((f,i)=>`<div class="v11-row"><span>▣ ${esc(f)}</span><button data-fdel="${i}">×</button></div>`).join('');p.querySelector('#v11AddFolder').onclick=()=>{const f=p.querySelector('#v11FolderName').value.trim().replace(/^\/|\/$/g,'');if(f&&!state.folders.includes(f)){state.folders.push(f);save();list()}};p.querySelector('#v11FolderList').onclick=e=>{const b=e.target.closest('[data-fdel]');if(b){state.folders.splice(+b.dataset.fdel,1);save();list()}};list()};
$('#v11Backup').onclick=()=>{const blob=new Blob([JSON.stringify({app:'Neon Notes',v11:state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='neon-notes-v1.1-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#v11Restore').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(!d.v11)throw Error('Not a v1.1 backup');state={...state,...d.v11};save();alert('Neon Notes v1.1 data restored.')}catch(err){alert('Restore failed: '+err.message)}e.target.value=''};
// Read common NeonOS accent preferences when available; retain app picker as fallback.
function syncAccent(){for(const k of ['neonOSAccent','neonosAccent','neonAccent','osAccentColor']){const c=localStorage.getItem(k);if(c&&/^#[0-9a-f]{3,8}$/i.test(c)){document.documentElement.style.setProperty('--accent',c);document.documentElement.style.setProperty('--purple',c);break}}}syncAccent();window.addEventListener('storage',e=>{if(/accent/i.test(e.key||''))syncAccent()});
})();
